### ISSUE TITLE
Discusión y Decisión sobre: Responsive

### ISSUE THREAD

**Issue by RominaRomano** [ArgLogan2/inmobiliaria#21]
Desde hoy y hasta el día viernes tienen el tiempo para dejar definido cómo trabajarán. La creación de esta issue es para dejar plasmado en los comentarios de la misma, sus opiniones, conversaciones y acuerdos, lo cual no quita y sería muy conveniente que tuvieran armado un grupo de wsp para front estático, como se sugirió en el chat del grupo gral.
Aprovechen, en principio, también, para trasladar esta issue a "en proceso" y a "hecho" en cada oportunidad, como lo mostró Juanjo en el video que preparó y que esta en el drive del propyecto. 
Una vez determinada la forma en que llevarán a cavo el responsive de la app, deberá quienes ustedes determinen, escoger la issue destinada a dicho trabajo, del proyecto Sprint 1 (otra oportunidad) y aplicar la metodología definida a la home-page (incluiyendo a los shareds components).

**Comment by RominaRomano** [comment]
En este espacio pueden generar el debate y definir la metodología a implementar... Mucha Suerte!

**Comment by lautarobg2** [comment]
Yo sugiero usar bootstrap para pequeñas cosas, algunos artilugios como medidas en % y media queries para otras.

**Comment by RominaRomano** [comment]
Paso esta issue a "hecho" pues interpreto que el resto de participantes del fron estático acuerdan con Lautaro sobre la forma de hacer el responsive de cada page. En principio deben dejar bien la home page y los shareds antes de encarar otras vistas.
